##########################################
### SAMPLE
##########################################

# User
userId: "<samplify userId>"  # e.g. userid: "kolart"
userEmail: "<userEmail>"     # e.g. userEmail: "kolart@uw.edu"

# Sample
sampleDirectory: "<full path to sample directory>"                  # e.g. sampleDirectory: "/net/nwgc/vol1/data/processed/samples/123456/WHOLE_GENOME"
sampleQCDirectory: "<full path to sample QC directory>"             # e.g. sampleQCDirectory: "/net/nwgc/vol1/data/processed/samples/123456/WHOLE_GENOME/qc"
samplePolymorphicQCDirectory: "<full path to sample QC directory>"  # e.g. samplePolymorphicQCDirectory: "/net/nwgc/vol1/data/processed/samples/123456/WHOLE_GENOME/polymorphicQC"
sampleId: <samplify sampleId>                                       # e.g sampleId: 123456
libraryId: <samplify libraryId>                                       # e.g libraryId: 123456

# Target
sequencingTarget: "<name of sequencing target>"                      # e.g. sequencingTarget: "nimblegen_solution_V2refseq_2010"
sequencingTargetIntervalsList: "<full path to intervals.list file>"  # e.g. sequencingTargetIntervalsList: "/net/nwgc/vol1/references/human/grc38/targets/nimblegen_solution_V2refseq_2010/nimblegen_solution_V2refseq_2010.grc38.intervals.list"
targetListFile: "<full path to target .list file>"                   # e.g. targetListFile: "/net/nwgc/vol1/references/human/hg19/targets/nimblegen_solution_V2refseq_2010/nimblegen_solution_V2refseq_2010.hg19.list"
  # sequencingTargetIntervalsDirectory should be null unless running analysis by chromosome
sequencingTargetIntervalsDirectory: "<full path to directory with chromosome intervals list files>"  # e.g. sequencingTargetIntervalsDirectory: "/net/nwgc/vol1/references/human/grc38/targets/nimblegen_solution_V2refseq_2010"
sequencingTargetBedFile: "<full path to bed file>"                                                   # e.g sequencingTargetBedFile: "/net/nwgc/vol1/references/human/grc38/targets/nimblegen_solution_V2refseq_2010/nimblegen_solution_V2refseq_2010.grc38.bed"

# Reference Genome
referenceGenome: "<full path to reference genome fasta>"        # e.g. referenceGenome: "/net/nwgc/vol1/references/human/grc38/genome/assembly_bwa_0.7.15/hs37d5.fa"
dbSnp: "<full path to dbSnp file>"                              # e.g. dbSnp: "/net/nwgc/vol1/references/human/grc38/genome/assembly_bwa_0.7.15/Homo_sapiens_assembly38.dbsnp138.vcf" (grc38)
                                                                # e.g. dbSnp: "/net/nwgc/vol1/references/human/snps/dbSNP/dbSNP138.vcf" (hg19)
goldStandardIndels: "<full path to gold standard indels file>"  # e.g. goldStandardIndels: "/net/nwgc/vol1/references/human/grc38/genome/assembly_bwa_0.7.15/Mills_and_1000G_gold_standard.indels.hg38.vcf"
knownIndels: "<full path to known indels file>"                 # e.g. knownIndels: "/net/nwgc/vol1/references/human/rc38/genome/assembly_bwa_0.7.15/Homo_sapiens_assembly38.known_indels.vcf"
referenceAbbr: "<reference genome abbreviation>"                # e.g. referenceAbbr: "grc38"

# Contamination
  # Leave null to use default file path 
contaminationUDPath: "<full path to contamination UD file>"     # e.g. contaminationUDPath: "/net/nwgc/vol1/references/human/grc38/contamination/1000g.twist_plus_refseq_10-31-2018.AF1p.b38.vcf.gz.UD"
contaminationBedPath: "<full path to contamination Bed file>"   # e.g. contaminationBedPath: "/net/nwgc/vol1/references/human/grc38/contamination/1000g.twist_plus_refseq_10-31-2018.AF1p.b38.vcf.gz.bed"
contaminationMeanPath: "<full path to contamination Mean file>" # e.g. contaminationMeanPath: "/net/nwgc/vol1/references/human/grc38/contamination/1000g.twist_plus_refseq_10-31-2018.AF1p.b38.vcf.gz.mu"
  # Custom contamination target
isCustomContaminationTargetSample: "<true or false based on if the sample has a custom contamination target>" #e.g. isCustomTargetContaminationSample: true
customContaminationTargetReferenceVCF: "<full path to VCF file for a custom contamination target>"            #e.g. customTargetContaminationReferenceVCF: "/net/nwgc/vol1/references/human/hg19/snps/verifyBamId/hapmap_3.3.b37.sites.vcf"

# Fingerprint
fingerprintBedFile:	"<full path to fingerprint bed file>"			# e.g. fingerprintBed: "/net/nwgc/vol1/references/human/grc38/targets/fingerprint_grc38_open_array.bed"


# Semi optional input files. Each yaml should have exactly one of mappedBams, mergedBam, or filteredGVCF depending on the portion of the pipeline meant to run.

# LibraryInfo - List of fastq files that need mapping and associated (optional) read group info
flowCellLaneLibraries:
  - fastq1: "<full path to the fastq1 file>"
    fastq2: "<full path to the fastq2 file>"
    library: "<samplify libraryId>"
    flowCell: "<flowcell ID>"
    lane: "<lane ID>"
    runDate: "<Timestamp from sequencer>"
    # barcode: "<Barcode from flowcell>" might remove this
  - fastq1: "<full path to the fastq1 file>"
    fastq2: "<full path to the fastq2 file>"
    library: "<samplify libraryId>"
    flowCell: "<flowcell ID>"
    lane: "<lane ID>"
    runDate: "<Timestamp from sequencer>"
    # barcode: "<Barcode from flowcell>" might remove this

# Bams  - Bam files that have been mapped (to merge together) 
mappedBams:
  - "<full path to first mapedBam>"
  - "<full path to second mappedBam>"
  - "<repeat for more bams>"
# e.g.
#bams:
#  - "/net/nwgc/vol1/home/kolart/nextflow_library_merge_test/downsampled_1.bam"
#  - "/net/nwgc/vol1/home/kolart/nextflow_library_merge_test/downsampled_2.bam"

# mergedBam (for running qc on an already existing merged bam)
mergedBam: "<full path to a merged bam that contains nm tags>"
# e.g.
#mergedBam: /net/nwgc/vol1/home/kolart/pacbio_merged_test.bam

# filteredGVCF (for running polymorphic qc on already a smaple with variants already called)
filteredGVCF: "<full path to a filtered_gvcf file>" # e.g. /net/nwgc/vol1/home/kolart/

# Optional (Already defaulted in nextflow.config file to organism=Homo sapiens, isGRC38=false)
organism: "<species other than Homo sapiens>"  # e.g. organism: "Mus musculus"
isGRC38: "<true if grc38>"                     # e.g. isGRC38: true
